# Generated by Django 5.0.7 on 2024-07-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
